version: "3.9"

services:
  postgres:
    command:
      - "postgres"
    image: postgres
    environment:
      - POSTGRES_DB=immutable_stack
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "6337:5432"